=== zhouand000/ARPG/src/arpg/assets/events/EventFile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" targetNamespace="http://www.w3schools.com"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="eventfile" type="w3s:eventfileType"
		xmlns:w3s="http://www.w3schools.com" />
	<xs:complexType name="choiceType" mixed="true">
		<xs:sequence>
			<xs:element type="xs:string" name="text" minOccurs="0" />
			<xs:element type="w3s:eventrefType" name="eventref"
				minOccurs="0" xmlns:w3s="http://www.w3schools.com" />
			<xs:element type="w3s:eventType" name="event" minOccurs="0"
				xmlns:w3s="http://www.w3schools.com" />
			<xs:element type="w3s:effectType" name="effect" maxOccurs="unbounded"
				minOccurs="0" xmlns:w3s="http://www.w3schools.com" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="soundType" mixed="true">
		<xs:sequence>
			<xs:element type="xs:string" name="biome" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="xs:string" name="place" minOccurs="0" />
			<xs:element type="w3s:regionType" name="region" minOccurs="0"
				xmlns:w3s="http://www.w3schools.com" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="load" use="optional" />
		<xs:attribute type="xs:string" name="replace" use="optional" />
		<xs:attribute type="xs:string" name="biome" use="optional" />
		<xs:attribute type="xs:string" name="location" use="optional" />
		<xs:attribute type="xs:string" name="region" use="optional" />
		<xs:attribute type="xs:string" name="name" use="optional" />
	</xs:complexType>
	<xs:complexType name="modifierType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="stat" use="optional" />
				<xs:attribute type="xs:string" name="type" use="optional" />
				<xs:attribute type="xs:string" name="amount" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="locationType" mixed="true">
		<xs:sequence>
			<xs:element type="xs:string" name="biome" maxOccurs="unbounded"
				minOccurs="0" />
			<xs:element type="xs:string" name="place" minOccurs="0" />
			<xs:element type="w3s:regionType" name="region" minOccurs="0"
				xmlns:w3s="http://www.w3schools.com" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="biome" use="optional" />
		<xs:attribute type="xs:string" name="location" use="optional" />
		<xs:attribute type="xs:string" name="region" use="optional" />
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:string" name="load" use="optional" />
		<xs:attribute type="xs:string" name="replace" use="optional" />
	</xs:complexType>
	<xs:complexType name="eventfileType">
		<xs:sequence>
			<xs:element type="w3s:eventType" name="event" maxOccurs="unbounded"
				minOccurs="0" xmlns:w3s="http://www.w3schools.com" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="eventType" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element type="w3s:locationType" name="location"
				xmlns:w3s="http://www.w3schools.com" />
			<xs:element type="xs:string" name="text" />
			<xs:element type="w3s:choiceType" name="choice"
				xmlns:w3s="http://www.w3schools.com" />
			<xs:element type="w3s:soundType" name="sound"
				xmlns:w3s="http://www.w3schools.com" />
		</xs:choice>
		<xs:attribute type="xs:string" name="ID" use="optional" />
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:string" name="standalone" use="optional" />
	</xs:complexType>
	<xs:complexType name="eventrefType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="ID" />
				<xs:attribute type="xs:string" name="name" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="effectType">
		<xs:sequence>
			<xs:element type="w3s:modifierType" name="modifier"
				xmlns:w3s="http://www.w3schools.com" />
		</xs:sequence>
		<xs:attribute type="xs:string" name="type" use="optional" />
		<xs:attribute type="xs:string" name="name" use="optional" />
	</xs:complexType>
	<xs:complexType name="regionType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="any" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== zhouand000/ARPG/src/arpg/assets/events/Events.xml
<?xml version="1.0" encoding="UTF-8"?>

<eventfile xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="file:./EventFile.xsd">

	<event ID="Start" name="Start" standalone="true">
		<location biome="$(ANY)" location="Empty" region="$(ANY)" />
		<text>
			Tip: Pay attention to your choices, and each event's text. There
			may be useful information.
		</text>
		<choice>
			<text>Start.</text>
		</choice>
	</event>

	<event ID="MysteriousTemple" name="Mysterious Temple" standalone="true">
		<location name="Mysterious Temple">
			<biome>Forest</biome>
			<biome>Jungle</biome>
			<biome>Desert</biome>
			<biome>Mountain</biome>
			<place>Mysterious Temple Exterior</place>
			<region any="true" />
		</location>
		<sound load="$(List.DARK)" />
		<location load="$(this.location)" replace="true" />
		<sound load="$(this.soundlist)" replace="true" />
		<text>You arrive at a mysterious temple.</text>
		<choice>
			<text>Enter.</text>
			<eventref ID="InsideMysteriousTemple" name="Mysterious Temple" />
		</choice>
		<choice>
			<text>Leave.</text>
		</choice>
	</event>

	<event ID="InsideMysteriousTemple" name="Inside the Mysterious Temple"
		standalone="false">
		<location>
			<place>Mysterious Temple Interior</place>
		</location>

		<location load="$(this.location)" replace="false" />
		<sound replace="false" />
		<text>There are two doors, plus the exit.</text>
		<choice>
			Take the left door.
			<event>
				A teleport trap activates, and returns you to the outside of the
				temple. The temple door seals behind you.
				<choice>
					<text>Continue.</text>
				</choice>
			</event>
		</choice>
		<choice>
			<text>The door leads to a pit.</text>
			<effect type="OneTime">
				<modifier stat="Health" type="multiplicative" amount="50%" />
			</effect>
			<effect name="Broken Leg" type="Status">
				<modifier stat="speed" type="multiplicative" amount="50%" />
			</effect>
		</choice>

	</event>

</eventfile>
